{
 "title": "Home",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Übersicht", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "homematicip_temperature_actual", "legendFormat": "{{room}}" },
    {
     "expr": "hue_sensor_value{type=\"ZLLTemperature\"}/100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Rooms",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "hue_group_on{type=\"Room\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Temperatur Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temperatur Gang",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "celsius" }
     ],
     "targets": [
      {
       "expr": "hue_sensor_value{type=\"ZLLTemperature\"}/100",
       "legendFormat": "Acutal"
      }
     ]
    },
    {
     "title": "Temperatur Bad",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "celsius" }
     ],
     "targets": [
      {
       "expr": "homematicip_temperature_actual{room=\"Badezimmer\"}",
       "legendFormat": "Acutal"
      },
      {
       "expr": "homematicip_temperature_setpoint{room=\"Badezimmer\"}",
       "legendFormat": "Setpoint"
      },
      {
       "expr": "homematicip_valve_position{room=\"Badezimmer\"}",
       "legendFormat": "Ventilöffnung"
      }
     ]
    },
    {
     "title": "Temperatur Wohnzimmer",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "celsius" }
     ],
     "targets": [
      {
       "expr": "homematicip_temperature_actual{room=\"Wohnzimmer\"}",
       "legendFormat": "Acutal"
      },
      {
       "expr": "homematicip_temperature_setpoint{room=\"Wohnzimmer\"}",
       "legendFormat": "Setpoint"
      },
      {
       "expr": "homematicip_valve_position{room=\"Wohnzimmer\"}",
       "legendFormat": "Ventilöffnung"
      }
     ]
    }
   ]
  },
  {
   "title": "Licht Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Light Brightness",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "(min(hue_light_brightness*hue_light_on) by (name)) /254",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Battery levels",
     "type": "table-old",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
     "targets": [
      {
       "expr": "min(hue_sensor_battery{type=~\"(ZLLPresence|ZLLSwitch)\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  }
 ]
}