- name: Run apt update
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: Update all packages to their latest version
  apt:
    name: "*"
    state: latest
  become: yes

- name: install required packages
  apt:
    name: "{{ packages_to_install }}"
    state: latest
  become: yes

- name: Cleanup unused packages
  apt:
    name: "{{ packages_to_remove }}"
    state: absent
  become: yes

- name: Cleanup (autoclean and autoremove)
  apt:
    autoclean: yes
    autoremove: yes
  become: yes
