- name: Check if swap file exists
  stat:
    path: "{{ swap_path }}"
  register: swap_file_check
  become: true

- name: Create swap file
  command: fallocate -l {{ swap_size }} {{ swap_path }}
  when: not swap_file_check.stat.exists
  become: true

- name: Change swap file permissions
  file:
    path: "{{ swap_path }}"
    owner: root
    group: root
    mode: 0600
  when: not swap_file_check.stat.exists
  become: true

- name: Format swap file
  command: "mkswap {{ swap_path }}"
  when: not swap_file_check.stat.exists
  become: true

- name: Write swap entry in fstab
  mount:
    name: none
    src: "{{ swap_path }}"
    fstype: swap
    opts: sw
    passno: '0'
    dump: '0'
    state: present
  become: true

- name: Turn on swap
  command: swapon -a
  when: not swap_file_check.stat.exists
  become: true
  notify: touch reboot file

- name: Set swappiness
  sysctl:
    name: vm.swappiness
    value: '1'
  become: true
