- name: Create the hue_exporter group
  group:
    name: "{{ _hue_exporter_system_group }}"
    state: present
    system: true
  when: _hue_exporter_system_group != "root"

- name: Create the hue_exporter user
  user:
    name: "{{ _hue_exporter_system_user }}"
    groups: "{{ _hue_exporter_system_group }}"
    append: true
    shell: /usr/sbin/nologin
    system: true
    create_home: false
    home: /
  when: _hue_exporter_system_user != "root"

- name: Download hue_exporter binary to localhost
  become: false
  get_url:
    url: "{{ download_url }}"
    dest: "/tmp/hue_exporter-{{ hue_exporter_version }}-{{ ansible_architecture }}"
    mode: 0755
    owner: root
    group: root
  register: _download_binary
  until: _download_binary is succeeded
  retries: 5
  delay: 2
  delegate_to: localhost
  check_mode: false

- name: Copy binary to server
  copy:
    src: "/tmp/hue_exporter-{{ hue_exporter_version }}-{{ ansible_architecture }}"
    dest: "{{ _hue_exporter_binary_install_dir }}/hue_exporter"
    mode: 0755
    owner: root
    group: root
  notify: restart hue_exporter
